### ISSUE TITLE
If a post has multiple images, it will only download the first in the set

### ISSUE THREAD

**Issue by AlexBezuska** [mannynotfound/mediascrape#3]
I am working on a fix for this, I will report back soon.

**Comment by mannynotfound** [comment]
oooh Ive actually solved this locally on my machine. I ended up giving them indexes so it would save like `<user>_<id>_1`, `<user>_<id>_2` etc.. I can push it up later today or look at your PR if youve already solved it

**Comment by AlexBezuska** [comment]
I haven't been able to figure it out yet but I am new to python (I mostly work in JS) 
if you could push that that would be awesome!

**Comment by AlexBezuska** [comment]
Actually I figured out a fix, I will have 2 new pull requests soon, but if your multiple photos post fix is cleaner just use yours no feelings will be hurt haha.

**Comment by mannynotfound** [comment]
fixed in https://github.com/mannynotfound/mediascrape/pull/5
